Models/AccessRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ScannerApp.Models
{
    public class AccessRecord
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Key]
        public string id { get; set; }
        [Display(Name = "Time")]
        public DateTime recordTime { get; set; }
        public string passType { get; set; }
        [Display(Name = "Device")]
        public string sn { get; set; } 

        [Display(Name = "Device Name")]
        public string equipName { get; set; }
        [Display(Name = "Photo")]
        public string photoUrl { get; set; }
        public string basePhotoUrl { get { return "http://175.143.69.73:8085" + photoUrl; } }
        public string photoSize { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }       
        public string phone { get; set; }
        [Display(Name = "Phone")]
        public string MyPhone
        {
            get
            {
                return phone.Length > 11 ? phone.Substring(5) : phone;
            }
        }
        public string arType { get; set; }
        [Display(Name = "Temperature")]
        public string temperature { get; set; }
        public string deptId { get; set; }
        [Display(Name = "Dept")]
        public string deptName { get; set; }
        [Display(Name = "Card")]
        public string cardNum { get; set; }
    }
}

Controllers/AccessRecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ScannerApp.Models;

namespace ScannerApp.Controllers
{
    public class AccessRecordsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AccessRecords
        public ActionResult Index(string currentFilter, string searchString, int? page, DateTime? dateFrom, DateTime? dateTo)
        {
            DateTime dtf = ViewBag.dtF = DateTime.Now;
            if (dateFrom != null)
            {
                dtf = ViewBag.dtF = Convert.ToDateTime(dateFrom);
            }

            ViewBag.dtT = DateTime.Now;
            DateTime dtt = DateTime.Now.AddDays(1);
            if (dateTo != null)
            {
                ViewBag.dtT = Convert.ToDateTime(dateTo);
                dtt = Convert.ToDateTime(dateTo).AddDays(1);
            }

            if (searchString != null)
            {
                searchString = searchString.ToLower();
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<AccessRecord> list = null;
            string client = User.Identity.Name;

            if (User.IsInRole("Admin"))
            {
                list = db.AccessRecords
                    .Where(_ => !string.IsNullOrEmpty(_.temperature))
                    .Where(_ => _.recordTime >= dtf.Date)
                    .Where(_ => _.recordTime <= dtt.Date)
                    .OrderByDescending(_ => _.recordTime).ToList();
            }
            else
            {

                list = (from d in db.Devices
                        join acc in db.AccessRecords on d.sn equals acc.sn
                        where d.client == User.Identity.Name && !string.IsNullOrEmpty(acc.temperature)
                        select acc).OrderByDescending(_ => _.recordTime).ToList();

                // list = db.AccessRecords.OrderByDescending(_ => _.recordTime).ToList();
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(s => s.name.ToLower().Contains(searchString)
                                       || s.phone.ToLower().Contains(searchString)
                                       || s.sn.ToLower().Contains(searchString)
                                       || (s.deptName.ToLower().Contains(searchString) || string.IsNullOrEmpty(searchString) && string.IsNullOrEmpty(s.deptName))
                                       || s.equipName.ToLower().Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));

            //  return View(db.AccessRecords.ToList());
        }

        // GET: AccessRecords/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessRecord accessRecord = db.AccessRecords.Find(id);
            if (accessRecord == null)
            {
                return HttpNotFound();
            }
            return View(accessRecord);
        }

        // GET: AccessRecords/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AccessRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,recordTime,passType,sn,equipName,photoUrl,photoSize,name,phone,arType,temperature,deptId,deptName,cardNum")] AccessRecord accessRecord)
        {
            if (ModelState.IsValid)
            {
                db.AccessRecords.Add(accessRecord);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accessRecord);
        }

        // GET: AccessRecords/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessRecord accessRecord = db.AccessRecords.Find(id);
            if (accessRecord == null)
            {
                return HttpNotFound();
            }
            return View(accessRecord);
        }

        // POST: AccessRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,recordTime,passType,sn,equipName,photoUrl,photoSize,name,phone,arType,temperature,deptId,deptName,cardNum")] AccessRecord accessRecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(accessRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accessRecord);
        }

        // GET: AccessRecords/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessRecord accessRecord = db.AccessRecords.Find(id);
            if (accessRecord == null)
            {
                return HttpNotFound();
            }
            return View(accessRecord);
        }

        // POST: AccessRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AccessRecord accessRecord = db.AccessRecords.Find(id);
            db.AccessRecords.Remove(accessRecord);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/AccessRecords/Create.cshtml
@model ScannerApp.Models.AccessRecord

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccessRecord</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recordTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recordTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recordTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.equipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.equipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.equipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.arType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.arType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.arType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.temperature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.temperature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.temperature, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cardNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cardNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cardNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/AccessRecords/Delete.cshtml
@model ScannerApp.Models.AccessRecord

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccessRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.recordTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recordTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.equipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photoSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photoSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.arType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.arType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.temperature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.temperature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cardNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cardNum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/AccessRecords/Details.cshtml
@model ScannerApp.Models.AccessRecord

@{
    ViewBag.Title = "Details";
}

<h2></h2>

<div>
    <h4>Access Record</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photoUrl)
        </dt>

        <dd>
            <img src="http://175.143.69.73:8085/@Url.Content(Model.photoUrl)" height=250 />
            <hr />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.temperature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.temperature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.recordTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recordTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.equipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cardNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cardNum)
        </dd>

    </dl>
</div>
<p>   
    @Html.ActionLink("Back to List", "Index")
</p>

Views/AccessRecords/Edit.cshtml
@model ScannerApp.Models.AccessRecord

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccessRecord</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.recordTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recordTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recordTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.equipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.equipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.equipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.arType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.arType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.arType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.temperature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.temperature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.temperature, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cardNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cardNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cardNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/AccessRecords/Index.cshtml
@model PagedList.IPagedList<ScannerApp.Models.AccessRecord>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Access Record";
}

<h3>Access Records</h3>

@using (Html.BeginForm())
{
    <div style="float:left">
        From :  <input type="date" name="dateFrom" id="dateFrom" class="date_picker" value="@string.Format("{0:yyyy-MM-dd}", ViewBag.dtF)">
        To : <input type="date" name="dateTo" id="dateTo" class="date_picker" value="@string.Format("{0:yyyy-MM-dd}", ViewBag.dtT)">
        Search : @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </div>

    <p style="float:right; color:red;">
        Temp >= 37.5 are red.
    </p>
}

<table class="table">
    <tr>
        <th>
            Photo
        </th>
        <th>
            Name
        </th>
        <th>
            Phone
        </th>
        <th>
            Temperature
        </th>
        <th>
            Time
        </th>
        <th>
            Device
        </th>
        <th>
            Device Name
        </th>
        <th>
            Department Name
        </th>
        <th>
            Card Num
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        string name = item.name == "" ? "Stranger" : item.name;

        <tr style='color: @( Convert.ToDecimal( item.temperature.Substring(0,4)) >= Convert.ToDecimal( 37.5 )? "red" : "black");'>
            <td>
                <img src="http://175.143.69.73:8085/@Url.Content( item.photoUrl)" height="60" alt="Image" />
            </td>
            <td style='color:@(name == "Stranger"? "blue": "black")'>
                @Html.DisplayFor(modelItem => name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MyPhone)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.temperature)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.recordTime)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.sn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.equipName)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.deptName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cardNum)
            </td>
            <td>
                <a href="@Url.Action("Details", "AccessRecords",new { id = item.id })" class="btn btn-info" data-toggle="tooltip" title="Details">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, datefrom = ViewBag.dtF, dateTo = ViewBag.dtT }))

<script>
    $(function () { $("[data-toggle = 'tooltip']").tooltip(); });

    $('.date_picker').datepicker();

</script>