Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ScannerApp.Models
{
    public class Device
    {
        [Key]
        public string id { get; set; }
        [ScaffoldColumn(false)]
        public string createUserId { get; set; }
        [Display(Name = "Device Name")]
        public string equipName { get; set; }
        [ScaffoldColumn(false)]
        public string isBind { get; set; }
        [ScaffoldColumn(false)]
        public string softVersion { get; set; }
        [Display(Name = "Device ID")]
        public string sn { get; set; }
        [ScaffoldColumn(false)]
        public string password { get; set; }
        [ScaffoldColumn(false)]
        public string ip { get; set; }
        [ScaffoldColumn(false)]
        public string status { get; set; }
        [ScaffoldColumn(false)]
        public string token { get; set; }
        [ScaffoldColumn(false)]
        public string createTime { get; set; }
        [ScaffoldColumn(false)]
        public string updateTime { get; set; }
        [ScaffoldColumn(false)]
        public string imUserId { get; set; }
        [ScaffoldColumn(false)]
        public string imToken { get; set; }
        [ScaffoldColumn(false)]
        public string appId { get; set; }
        [ScaffoldColumn(false)]
        public string temperature { get; set; }
        [ScaffoldColumn(false)]
        public string deptId { get; set; }
        [Display(Name = "Department")]
        public string deptName { get; set; }
        [Display(Name = "Company")]
        public string companyName { get; set; }
        [ScaffoldColumn(false)]
        public string dataType { get; set; }
        [ScaffoldColumn(false)]
        public string validateTime { get; set; }

        [Display(Name = "Client")]
        public string client { get; set; }

        [Display(Name = "Online")]
        public string onlineStatus { get; set; }


    }
}

Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using QRCoder;
using ScannerApp.Models;

namespace ScannerApp.Controllers
{
    public class DevicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Devices
        public ActionResult Index(int? page)
        {
            string client = User.Identity.Name;
            List<Device> list = null;

            if (User.IsInRole("Admin"))
            {
                list = db.Devices.ToList();
            }
            else
            {
                list = db.Devices.Where(_ => _.client == client).ToList();
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        
        public ActionResult GenerateQR(string sn)
        {

            string uri1 = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
            string qr = uri1 + "/Selfregistration?id=" + sn;

            using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator qrGenerator = new QRCodeGenerator();
                QRCodeData data = qrGenerator.CreateQrCode(qr, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCoder.QRCode(data);

                using (Bitmap bitMap = qrCode.GetGraphic(20))
                {
                    bitMap.Save(ms, ImageFormat.Png);
                    ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }

            return View();
        }


        // GET: Devices/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            ViewBag.Client = new SelectList(db.Users.ToList(), "UserName", "UserName");

            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,createUserId,equipName,isBind,softVersion,sn,password,ip,status,token,createTime,updateTime,imUserId,imToken,appId,temperature,deptId,deptName,companyName,dataType,validateTime, client")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            if (device.client == null)
            {
                device.client = "";
            }

            ViewBag.Client = new SelectList(db.Users.ToList(), "UserName", "UserName", device.client);
            // ViewBag.Default = device.client;
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,createUserId,equipName,isBind,softVersion,sn,password,ip,status,token,createTime,updateTime,imUserId,imToken,appId,temperature,deptId,deptName,companyName,dataType,validateTime,client")] Device device)
        {
            if (ModelState.IsValid)
            {
                Device entity = db.Devices.Find(device.id);
                entity.client = device.client;

                db.Entry(entity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Devices/Create.cshtml
@model ScannerApp.Models.Device

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Device</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.equipName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.equipName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.equipName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Client", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownList("client", (SelectList)ViewBag.Client, " ")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Devices/Delete.cshtml
@model ScannerApp.Models.Device

@{
    ViewBag.Title = "Delete";
}

<h2></h2>

<h3>Are you sure you want to delete this device?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.equipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Devices/Details.cshtml
@model ScannerApp.Models.Device

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.equipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Devices/Edit.cshtml
@model ScannerApp.Models.Device

@{
    ViewBag.Title = "Edit";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Device</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.equipName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">           
            @Html.TextBoxFor(model => model.equipName, htmlAttributes: new { disabled = "disabled", @readonly = "readonly", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.equipName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">          
             @Html.TextBoxFor(model => model.sn, htmlAttributes: new { disabled = "disabled", @readonly = "readonly", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.sn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">           
            @Html.TextBoxFor(model => model.deptName, htmlAttributes: new { disabled = "disabled", @readonly = "readonly", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.client, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Client", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.client, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-warning" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Devices/GenerateQR.cshtml
@{
    ViewBag.Title = "GenerateQR";
}

<hr />
<div id="printableArea" style="padding:10px;">
    @if (ViewBag.QRCodeImage != null)
    {
        <img src="@ViewBag.QRCodeImage" alt="" style="height:200px;width:200px" />
    }
    <br />
    <br />
    <h3>1) Please scan the QR code by your mobile phone and fill up the registration form.</h3>
    <h3>2) Take selfie / select photo to complete registration.</h3>
    <hr />
</div>
<div style="padding:10px;">
    <input type="button" onclick="printDiv('printableArea')" value="Print QR!" class="btn btn-success" />
</div>
<div style="padding:10px;">
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    function printDiv(divName) {
        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;
    }
</script>

Views/Devices/Index.cshtml
@model PagedList.IPagedList<ScannerApp.Models.Device>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

@{
    ViewBag.Title = "Index";
}

<h2>Devices</h2>

<p>
    @* @Html.ActionLink("Create New", "Create")*@
    @*<a href="@Url.Action("Create", "Devices")" class="btn btn-warning"  data-toggle = "tooltip" title = "Create New">
            Create New
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </a>*@
</p>
<table class="table" >
    <tr>
        <th>
            Device Name
        </th>
        <th>
            Device
        </th>
        <th>
            Department
        </th>
        <th>
            Online
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.companyName)
            </th>*@
        <th>
            Client
        </th>
        <th></th>
    </tr >

    @foreach (var item in Model)
    {
        string status = item.onlineStatus == "1" ? "On" : "Off";
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.equipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deptName)
            </td>
            <td style='font-weight:@(status == "On"? "bold": ""); color:@(status == "On"? "green": "black")'>
                @Html.DisplayFor(modelItem => status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.client)
            </td>
            <td>
                <a href="@Url.Action("GenerateQR", "Devices",new { sn = item.sn })" class="btn btn-info btn-xs" data-toggle="tooltip" title="View QR">
                    <span class="glyphicon glyphicon-qrcode" aria-hidden="true"></span>
                </a>
                @*@Html.ActionLink("QR", "GenerateQR", new { sn = item.sn }, new { @class = "glyphicon glyphicon-log-in" }) |*@

                @if (User.IsInRole("Admin"))
                {
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.id })*@

                    <a href="@Url.Action("Edit", "Devices", new { id = item.id })" class="btn btn-info btn-xs" data-toggle="tooltip" title="Edit">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>

                    <a href="@Url.Action("Delete", "Devices",new { id = item.id })" class="btn btn-danger btn-xs" data-toggle="tooltip" title="Delete">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                }

                <a href="@Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~")Selfregistration?id=@item.sn"  target="_blank"  class="btn btn-warning btn-xs" data-toggle="tooltip" title="Visitor Registration">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </a>
                @*<a href="@Url.Action("Details", "Devices",new { id = item.id })" class="btn btn-info"  data-toggle = "tooltip" title = "Details">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        </a>
        <a href="@Url.Action("Delete", "Devices",new { id = item.id })" class="btn btn-danger"  data-toggle = "tooltip" title = "Delete">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </a>*@

                @*@Html.ActionLink("Details", "Details", new { id = item.id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.id })*@
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

<script>
    $(function () { $("[data-toggle = 'tooltip']").tooltip(); });
</script>