Controllers/UserListController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using ScannerApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ScannerApp.Controllers
{
    public class UserListController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        // GET: UserList
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            List<UserListViewModel> list = new List<UserListViewModel>();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PhoneSortParm = String.IsNullOrEmpty(sortOrder) ? "phone_desc" : "";
            ViewBag.RoleSortParm = String.IsNullOrEmpty(sortOrder) ? "role_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;


            list = (from user in db.Users
                    from userRole in user.Roles
                    join role in db.Roles on
                    userRole.RoleId equals role.Id
                    select new UserListViewModel()
                    {
                        UserID = user.Id,
                        UserName = user.UserName,
                        Email = user.Email,
                        Phone = user.PhoneNumber,
                        Role = role.Name
                    }).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(s => s.UserName.ToLower().Contains(searchString)
                                       || s.Phone.ToLower().Contains(searchString)
                                       || s.Role.ToLower().Contains(searchString)).ToList();
            }


            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(s => s.UserName).ToList();
                    break;
                case "phone_desc":
                    list = list.OrderBy(s => s.Phone).ToList();
                    break;
                case "role_desc":
                    list = list.OrderByDescending(s => s.Role).ToList();
                    break;
                default:
                    list = list.OrderBy(s => s.UserName).ToList();
                    break;
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        // GET: UserList/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserList/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var obj = (from user in db.Users
                       from userRole in user.Roles
                       join role in db.Roles on
                       userRole.RoleId equals role.Id
                       where user.Id == id
                       select new UserListViewModel()
                       {
                           UserID = user.Id,
                           UserName = user.UserName,
                           Email = user.Email,
                           Phone = user.PhoneNumber,
                           Role = role.Name
                       }).SingleOrDefault();

            if (obj == null)
            {
                return HttpNotFound();
            }

            ViewBag.Role = new SelectList(db.Roles.ToList(), "Name", "Name", obj.Role);

            return View(obj);
        }

        // POST: UserList/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "UserID,UserName,Email,Phone,Role")] UserListViewModel obj)
        {
            try
            {
                if (ModelState.IsValid)
                {                   
                    var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                    var user = UserManager.FindById(obj.UserID);
                    user.PhoneNumber = obj.Phone;
                    UserManager.RemoveFromRoles(obj.UserID, UserManager.GetRoles(obj.UserID).ToArray());
                    UserManager.AddToRole(obj.UserID, obj.Role);
                    UserManager.Update(user);

                    return RedirectToAction("Index");
                }
                return View(obj);
            }
            catch
            {
                return View();
            }
        }

        // GET: UserList/Delete/5
        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var obj = (from user in db.Users
                       from userRole in user.Roles
                       join role in db.Roles on
                       userRole.RoleId equals role.Id
                       where user.Id == id
                       select new UserListViewModel()
                       {
                           UserID = user.Id,
                           UserName = user.UserName,
                           Email = user.Email,
                           Phone = user.PhoneNumber,
                           Role = role.Name
                       }).SingleOrDefault();

            if (obj == null)
            {
                return HttpNotFound();
            }

            ViewBag.Role = new SelectList(db.Roles.ToList(), "Name", "Name", obj.Role);

            return View(obj);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {            
            try
            {               
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                var user = UserManager.FindById(id);                
                UserManager.RemoveFromRoles(id, UserManager.GetRoles(id).ToArray());
                 
                UserManager.Delete(user);

                return RedirectToAction("Index");                
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/UserList/Delete.cshtml
@model ScannerApp.Models.UserListViewModel

@{
    ViewBag.Title = "Delete";
}



<h3>Are you sure you want to delete this user?</h3>
<div>
     
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/UserList/Edit.cshtml
@model ScannerApp.Models.UserListViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserListViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserName, htmlAttributes: new { disabled = "disabled", @readonly = "readonly", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Role, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Role", null,null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/UserList/Index.cshtml
@model PagedList.IPagedList<ScannerApp.Models.UserListViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Users";
}

<h2>Clients</h2>

@*<p>
     @Html.ActionLink("New User", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
    <a href="@Url.Action( "Register","Account")" class="btn btn-warning" data-toggle="tooltip" title="New User">
        New User
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </a>
</p>*@

@using (Html.BeginForm())
{
    <p>
        Search: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("User Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            @* @Html.DisplayNameFor(model => model.UserName)*@
        </th>
        <th>
            @Html.ActionLink("Phone", "Index", new { sortOrder = ViewBag.PhoneSortParm, currentFilter = ViewBag.CurrentFilter })
            @* @Html.DisplayNameFor(model => model.Phone)*@
        </th>
        <th>
            Email
        </th>
        <th>
            @Html.ActionLink("Role", "Index", new { sortOrder = ViewBag.RoleSortParm, currentFilter = ViewBag.CurrentFilter })
            @* @Html.DisplayNameFor(model => model.Role)*@
        </th>
        <th>
            <a href="@Url.Action( "Register","Account")" class="btn btn-warning btn-xs" data-toggle="tooltip" title="New User">
                User
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                <a href="@Url.Action("Edit", "UserList",new { id = item.UserID })" class="btn btn-info btn-xs" data-toggle="tooltip" title="Edit">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Delete", "UserList",new { id = item.UserID })" class="btn btn-danger btn-xs" data-toggle="tooltip" title="Delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    }
</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))