Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ScannerApp.Models
{
    public class Staff
    {
        [Key]
        public string perId { get; set; }
        [Display(Name="Photo")]
        public string photoUrl { get; set; }

        public string basePhotoUrl { get { return "http://175.143.69.73:8085" + photoUrl; } }
        [Display(Name = "Name")]
        public string name { get; set; }
        
        public string phone { get; set; }
        [Display(Name = "Phone")]
        public string MyPhone {
            get { 

                return phone.Length > 11? phone.Substring(5): phone; 
            } 
        }

        [Display(Name = "Department Name")]
        public string deptName { get; set; }
        [ScaffoldColumn(false)]
        public string fiUrl { get; set; }
       
        [ScaffoldColumn(false)]
        public string imToken { get; set; }
        [ScaffoldColumn(false)]
        public string appId { get; set; }
        
        [ScaffoldColumn(false)]
        public string imUserId { get; set; }
        [ScaffoldColumn(false)]
        public string deptId { get; set; }
        [ScaffoldColumn(false)]
        public string personType { get; set; }
        [Display(Name = "Client")]
        public string job { get; set; }
        public DateTime ORDER_BY_DERIVED_0 { get; set; }

        [Display(Name = "Reg. Device")]
        public string emerPer { get; set; }

    }
}

Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ScannerApp.Models;

namespace ScannerApp.Controllers
{
    public class StaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Staffs
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                searchString = searchString.ToLower();
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            string client = User.Identity.Name;
            List<Staff> list = null;

            if (User.IsInRole("Admin"))
            {
                list = db.Staffs.Where(_ => !string.IsNullOrEmpty(_.photoUrl)).OrderByDescending(_ => _.ORDER_BY_DERIVED_0).ToList();
            }
            else
            {
                list = db.Staffs.Where(_ => _.job == client && !string.IsNullOrEmpty(_.photoUrl)).OrderByDescending(_ => _.ORDER_BY_DERIVED_0).ToList();
            }



            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(s => s.name.ToLower().Contains(searchString)
                                       || s.phone.ToLower().Contains(searchString)
                                       || s.deptName.ToLower().Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        // GET: Staffs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "perId,photoUrl,deptName,fiUrl,phone,imToken,appId,name,imUserId,deptId,personType")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "perId,photoUrl,deptName,fiUrl,phone,imToken,appId,name,imUserId,deptId,personType")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Staffs/Create.cshtml
@model ScannerApp.Models.Staff

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.perId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.perId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.perId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Staffs/Delete.cshtml
@model ScannerApp.Models.Staff

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this visitor!</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photoUrl)
        </dt>
        <dd>
            <img src="http://175.143.69.73:8085/@Url.Content(Model.photoUrl)" height=350 />
            <hr />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MyPhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MyPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.emerPer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.emerPer)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Staffs/Details.cshtml
@model ScannerApp.Models.Staff

@{
    ViewBag.Title = "Details";
}

<h2></h2>

<div>
    <h4>Visitor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.photoUrl)
        </dt>
        <dd>
            <img src="http://175.143.69.73:8085/@Url.Content(Model.photoUrl)" height=350 />
            <hr />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MyPhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MyPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.emerPer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.emerPer)
        </dd>
    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Staffs/Edit.cshtml
@model ScannerApp.Models.Staff

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.perId)

        <div class="form-group">
            @Html.LabelFor(model => model.photoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Staffs/Index.cshtml
@model PagedList.IPagedList<ScannerApp.Models.Staff>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Visitors";
}

<h2>Visitors</h2>

@using (Html.BeginForm())
{
    <p>
        Search: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Photo
        </th>
        <th>
            Name
        </th>
        <th>
            Phone
        </th>
        <th>
            Department
        </th>
        <th>
            Device
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @*@Html.DisplayFor(modelItem => item.photoUrl)*@
        <img src="http://175.143.69.73:8085/@Url.Content(item.photoUrl)" height="50" alt="Image" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MyPhone)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.deptName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.emerPer)
    </td>
    <td>
        <a href="@Url.Action("Details", "Staffs",new { id = item.perId })" class="btn btn-info" data-toggle="tooltip" title="Details">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        </a>

        <a href="@Url.Action("Delete", "Staffs",new { id = item.perId })" class="btn btn-danger" data-toggle="tooltip" title="Delete">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </a>

    </td>
</tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page , currentFilter = ViewBag.CurrentFilter }))

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(function () { $("[data-toggle = 'tooltip']").tooltip(); });
</script>